set gfn=IBM\ Plex\ Mono\ 11

set guicursor-=a:blinkon0
set guioptions+=c
set guioptions-=m
set guioptions-=T
set guioptions-=t
set guioptions-=e
"
" Disable scrollbars (real hackers don't use scrollbars for navigation!)
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L

colo gruvbox
