set gfn=IBM\ Plex\ Mono\ 15

if has('win32') || has ('win64')
    source ~/vimfiles/local
endif
"else
"    source ~/.vim/local
"endif

set guioptions+=c
set guioptions-=m
set guioptions-=T
set guioptions-=t
set guioptions-=e
"
" Disable scrollbars (real hackers don't use scrollbars for navigation!)
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L

" Disable cursor blinking in GUI
set guicursor+=a:blinkon0

colo gruvbox
