set gfn=IBM\ Plex\ Mono\ 11

if has('win32') || has ('win64')
    source ~/vimfiles/local
else
    source ~/.vim/local
endif

set guicursor-=a:blinkon0
set guioptions+=c
set guioptions-=m
set guioptions-=T
set guioptions-=t
set guioptions-=e
"
" Disable scrollbars (real hackers don't use scrollbars for navigation!)
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L

